### ISSUE TITLE
Please add this feature or fix this

### ISSUE THREAD

**Issue by mehedi696969** [VehanRajintha/Free-Unlimited-Google-Cloud-Backup-Magisk-Module#1]
Unblur and portrait feature not work in my pixel 6,after install this module.

**Comment by VehanRajintha** [comment]
> Unblur and portrait feature not work in my pixel 6,after install this module.

I will fix it and bring an update in the future

**Comment by mehedi696969** [comment]
Ok thanks bro.
Magic editor work fine,no problem with that.
Definitely add portrait light and unblur feature.
