### ISSUE TITLE
Question: Can this be applied on an Android VM or an emulator possibly in a server?

### ISSUE THREAD

**Issue by SurjitSahoo** [VehanRajintha/Free-Unlimited-Google-Cloud-Backup-Magisk-Module#3]
Rooting makes my phone useless for banking and official work, so unless I want to keep 2 phones at minimum is a no go. 
And the custom roms always come with one or the other issues.

So can we create a VM on an unraid or similar server and automatically backup everything from a folder?

**Comment by VehanRajintha** [comment]
yes
